staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: http://localhost:8545

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
