[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
quid = "CpCe1dCqRJ231arzyanw9H2cBeCwCR8LDvALWyNzS5DE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
startup_wait = "10000"
test = "yarn run test"
