// Auto-generated by deployment script
export const FACTORY_ADDRESS = "0xca71e5aaefc47f1a6ef0140b290b27bb4c5b79dc";
export const HELPERS_ADDRESS = "0xc44bb73163949e8a2e1a26bd6ac0252c764bf443";
export const SETTLEMENT_ADDRESS = "0xda232a954e55569900251bec5cf9ed82c2b9a01e";
export const BASKET_ADDRESS = "0x0865ce3b75f8ce49afb0af0efc1d87c7e2712116";
export const CHAIN_ID = 11155111;
