// Auto-generated by deployment script - do not edit manually
// Generated at block: 9026567
// Chain ID: 11155111 (Sepolia)

// Update these with your actual deployed addresses from the deployment logs
export const FACTORY_ADDRESS = '0xCa71e5AAefC47f1A6ef0140B290b27bB4C5B79dc';
export const HELPERS_ADDRESS = '0xc44bB73163949E8A2e1A26bD6Ac0252C764BF443';
export const SETTLEMENT_ADDRESS = '0xda232a954E55569900251bEc5CF9eD82C2b9A01e';

// For testing - these should be the dummy contract addresses
export const BASKET_ADDRESS = '0x0865cE3b75f8ce49afb0AF0EFc1D87c7e2712116';